### ISSUE TITLE
Delete unused files

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidmresults-examples#2]
The following files are duplicates and should be deleted from this repository:
- `#nidm.ttl#` in https://github.com/incf-nidash/nidmresults-examples/tree/master/ground_truth/voxel_FWE_p_05
- `VUncorrectedpdf.m` in https://github.com/incf-nidash/nidmresults-examples/tree/master/spm_voxelwise_p0001

**Comment by AlexBowring** [comment]
Resolved

**Comment by cmaumet** [comment]
Excellent! Thank you @AlexBowring
