### ISSUE TITLE
Document testing variant spreadsheet

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidmresults-examples#22]
@AlexBowring: can you add a page in the Wiki of this repository (cf. https://github.com/incf-nidash/nidmresults-examples/wiki) with a link to our spreadsheet listing the testing variants?

**Comment by AlexBowring** [comment]
Okay done it, let me know what you think.

**Comment by cmaumet** [comment]
This is great! In fact, this description would also be perfect for the [main README](https://github.com/incf-nidash/nidmresults-examples/blob/master/README.md). Could you update it as well (you can do that directly on GitHub using the "edit" button)? Thanks!
