### ISSUE TITLE
Add namespace prefixes in nidm.ttl ground truth voxel_FWE_p_05

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidmresults-examples#3]
Namespace prefixes are missing in [ground_truth/voxel_FWE_p_05/nidm.ttl](https://github.com/incf-nidash/nidmresults-examples/blob/master/ground_truth/voxel_FWE_p_05/nidm.ttl). Similarly to what was done in [ground_truth/voxel_uncorrected_p_001/nidm.ttl#L1-L4](https://github.com/incf-nidash/nidmresults-examples/blob/master/ground_truth/voxel_uncorrected_p_001/nidm.ttl#L1-L4), `@prefix` should be added at the beginning of the file to define `nidm:`, `prov:`, `rdfs:`...

**Comment by AlexBowring** [comment]
Resolved
