### ISSUE TITLE
Contrast masking needs more than 1 contrast

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidmresults-examples#9]
Hi @AlexBowring! Starting to run the FSL test examples... I have noticed that [fsl_contrast_mask](https://github.com/incf-nidash/nidmresults-examples/tree/master/fsl_contrast_mask) only has one contrast defined while what we would really need is two contrasts and then mask contrast 1 with contrast 2. Could you have a look into this? Thanks!

**Comment by AlexBowring** [comment]
Hi @cmaumet , I have uploaded new results with multiple contrasts, let me know if this is okay :)

**Comment by cmaumet** [comment]
Now implemented in #17.
